### ISSUE TITLE
A Jasmine Spec has timed out: Resetting the webdriver control flow

### ISSUE THREAD

**Issue by illninofan** [angular/protractor#1095]
Hi

I'm pretty new to protractor and currently using version 1.0.0-rc4

When I've got multiple specs, and I run them via protractor config.js, I get the following error

```
A Jasmine Spec has timed out: Resetting the webdriver control flow
```

with the first spec passing (logging into the website) but the next spec failing with the above line in the command prompt 

Any ideas?

**Comment by adtrsa** [comment]
Hi

I get a similar timeout error when running my protractor tests on a headless server.
Initially I tried getting the tests to run in Jenkins, but then realised I could replicate my error outside of Jenkins when executing from shell.

When I run the tests on my dev machine, no problem.

As soon as I run them on headless server (using either Xvfb or vncserver to provide display), I get the Jasmine timeout error.

I've tried it with or without selenium (latter by setting directConnect: true in protractor config), same result.  I've tried setting the allScriptsTimeout and jasmineNodeOpts: {defaultTimeoutInterval: timeout_in_millis} timeouts, but all that happens then is that the test takes as long as the largest timeout value to fail.

I am running the tests on Ubuntu 14.04 LTS, protractor version 1.6.1.

Test and configuration is dead simple.  Names of files reflect that this was for debugging Jenkins test runs :D

== BEGIN protractor_jenkins.conf ==
```
exports.config = {
  directConnect: true,
  chromeDriver: '../node_modules/protractor/selenium/chromedriver',
  capabilities: {
        browserName: 'firefox'
  },

  specs: ['e2e/jenkins.spec.js']
 };
```
== END ==

== BEGIN jenkins.spec.js ==
```
/**
Dead simple test to debug test execution on headless server.
*/
describe('angularjs homepage', function() {
  it('should have a title', function() {
    browser.get('http://www.angularjs.org');
    expect(browser.getTitle()).toEqual('AngularJS — Superheroic JavaScript MVW Framework');
  });
});
```
== END == 

Test run like so:
export DISPLAY=:0 && Xvfb :0 -ac & ./node_modules/protractor/bin/protractor test/protractor_jenkins.conf

Error log to follow (stripped project name/paths from output):

== BEGIN error log ==
```
[launcher] Running 1 instances of WebDriver
browser.getTitle() : [object Object]
A Jasmine spec timed out. Resetting the WebDriver Control Flow.
The last active task was: 
Protractor.get(http://www.angularjs.org/) - test for angular
node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:345:15)
    at [object Object].Protractor.executeAsyncScript_ (node_modules/protractor/lib/protractor.js:247:26)
    at [object Object].Protractor.get (node_modules/protractor/lib/protractor.js:467:8)
    at [object Object].<anonymous> (test/e2e/jenkins.spec.js:6:13)
    at node_modules/protractor/node_modules/jasminewd/index.js:94:14
    at [object Object].webdriver.promise.ControlFlow.runInNewFrame_ (node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1654:20)
    at [object Object].webdriver.promise.ControlFlow.runEventLoop_ (node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1518:8)
    at [object Object].wrapper [as _onTimeout] (timers.js:252:14)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
F

Failures:

  1) angularjs homepage should have a title
   Message:
     timeout: timed out after 30000 msec waiting for spec to complete
```
== END ==

**Comment by gvhelp** [comment]
I got the same issue : A Jasmine spec timed out. Resetting the WebDriver Control Flow.
The last active task was:

I am using 
C:\Dev\test>protractor --version
Version 1.8.0

Any suggestion!?

**Comment by d3day** [comment]
protractor 1.8.0 
same issue with firefox

**Comment by AksimO** [comment]
Same issue chrome. 
Every 10th test failing with  timeout error. (I run same test suite  20 times, got 2 timeout errors in a console).
I might be  important that ```restartBrowserBetweenTests: true```

```
   { applicationCacheEnabled: false,
     rotatable: false,
     mobileEmulationEnabled: false,
     chrome: { userDataDir: 'C:\\Users\\RRRR~1\\AppData\\Local\\Temp\\scoped_dir10544_2327' },
     takesHeapSnapshot: true,
     databaseEnabled: false,
     handlesAlerts: true,
     version: '42.0.2311.152',
     platform: 'XP',
     browserConnectionEnabled: false,
     nativeEvents: true,
     acceptSslCerts: true,
     'webdriver.remote.sessionid': '6266fa7f-c8c1-4645-8911-adf4ed8a9503',
     locationContextEnabled: true,
     webStorageEnabled: true,
     browserName: 'chrome',
     takesScreenshot: true,
     javascriptEnabled: true,
     cssSelectorsEnabled: true } }
```

**Comment by AksimO** [comment]
I checked it 3 different windows machine.
Simplest test that fails for me(with ```restartBrowserBetweenTests: true```)
 is: 
```
for (var i = 0; i <22 ; i ++) {
  (function (i) {
  describe('Test session', function () {
    it('Test', function () {
      console.log('i=', i);
      browser.driver.get('data:text/html,lots of text...');
      expect(true).toBe(true);
    });
  });
  })(i);
}
```
It looks like something wrong with newSession. It does not start new session for test N10 and N20

**Comment by AksimO** [comment]
I found that it's problem in jasminewd2. For some reason it starts suite 10 before suite is finished.
Workaround to use jasminewd instead of jasminewd2. In order to do it put in protractor config ```framework: 'jasmine'``` instead of ```framework: 'jasmine2'```.

**Comment by bitliner** [comment]
Same issue here, testing on IE9 inside a VM. 
Sometimes it fails (timeout), sometimes it doesn't.

```
TypeError: Cannot call method 'split' of undefined
    at Object.SpecDisplay.filterStackTraces (/app/node_modules/jasmine-spec-reporter/src/spec-display.js:110:24)
    at Object.SpecDisplay.displayErrorMessages (/app/node_modules/jasmine-spec-reporter/src/spec-display.js:102:25)

```

**Comment by gologox** [comment]
Same issue here. If you follow AksimO's suggestion above, it fixes the issue:
'jasmine' instead of framework: 'jasmine2'.

**Comment by bitliner** [comment]
It is already 'jasmine'. Unfortunately i dont have more details. I'll post
more as soon as i have them.



On Friday, May 29, 2015, gologox <notifications@github.com> wrote:

> Same issue here. If you follow AksimO's suggestion above, it fixes the
> issue:
> 'jasmine' instead of framework: 'jasmine2'.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular/protractor/issues/1095#issuecomment-106613486>
> .
>


-- 
*Giovanni Gaglione                            *

LinkedIn: http://lnkd.in/MyZGut
Telefono: +39 388 - 82.6666.2 / 0031-06.49.75.66.93 / 0031-06.11.06.22.17
Email: giovanni.gaglione@gmail.com
<giovanni.gaglione@gmail.com>Skype: bitliner

**Comment by AksimO** [comment]
Hint.

File ``jasmine-core/lib/jasmine-core/jasmine.js`` contains  constant ```var maximumSpecCallbackDepth = 20;``` and method ```QueueRunner.prototype.run```. Method  ```QueueRunner.prototype.run clearStack```  runs callback 9 times sync, then it wraps callback in a ```setTimeout(..., 0);```.
Because of this callback is triggered async, jasmine runs next spec before webdriver quite current session => webdriver does not start new session => jasmines show timeout error.

**Comment by rodrigomf24** [comment]
I don't know if this is a good solution but I noticed some of the requests on my angular app took a bit longer than 30000ms, so I changed in the config file " jasmineNodeOpts:{defaultTimeoutInterval: 60000} " to be 60000ms. Now it works perfectly and I don't get timeout errors.

**Comment by calystoramesh** [comment]
I got the same issue : A Jasmine spec timed out. Resetting the WebDriver Control Flow.
tried this solution following solution : 
1.  " jasmineNodeOpts:{defaultTimeoutInterval: 60000} " to be 60000ms.  - not works 
2.   'jasmine' instead of framework: 'jasmine2'. ..In my Test script I am using beforeAll , afterAll not possible go to do the solution 

Protractor version 2.5.1
please provide any other solution?
thanks in advance

**Comment by AksimO** [comment]
Do see timeout message every time, or some of tests a passing?

**Comment by calystoramesh** [comment]
some of the test passed then occurs this error

**Comment by AksimO** [comment]
@calystoramesh, I had similar issue, I solved in with monkey patch. Find in jasmine-core/jasmine.js  this line https://github.com/jasmine/jasmine/blob/master/lib/jasmine-core/jasmine.js#L660

change variable  ```maximumSpecCallbackDepth``` to 2000 does it have any effect for you?

**Comment by arturskeeled** [comment]
None of this has worked.
I am running in IE11 and no test passes.
Any news here?

**Comment by christoforosl** [comment]
@arturskeeled , I managed to make IE11  tests work. Only change was setting jasmineNodeOpts.defaultTimeoutInterval to 20000 (was 2000)  in protractor config.  
Changing maximumSpecCallbackDepth  did not have any effect.
My tests were passing in chrome, but not in ie11.

**Comment by arturskeeled** [comment]
@christoforosl Changing the webdriver from x64 to x32 worked for me.
Although a couple days later i had to change it back to x64, and i found that out by pure chance. Hope it doesn't break again.

Thanks, but I guess my issue was another one, because I had changed "defaultTimeoutInterval" to 120'000 and it still didn't work.

**Comment by makwanaparth94** [comment]
Getting the same error. 
I am also attaching a screenshot  of it .
Let me know the solutions of it 
Its an issue of my local machine requirement or a code issue?

Sometimes Script run on IE browser with their 3 instance and sometimes its not ruuning.

![image](https://cloud.githubusercontent.com/assets/28529639/26148470/593fb5c4-3b14-11e7-90e9-b27d2cc82c79.png)
![image](https://cloud.githubusercontent.com/assets/28529639/26148483/620fdd6e-3b14-11e7-8170-41d6a70af963.png)

**Comment by gologox** [comment]
I ended up just updating Protractor to the latest version and my Selenium
server and everything is great

**Comment by suzy123** [comment]
unable to update protractor to latest version by npm update protractor. Facing above issue.

**Comment by suzy123** [comment]
I have upgraded the protractor version,node,selenium server as well. Still facing the same issue.Can anyone provide any solution??

**Comment by gologox** [comment]
@suzy123 what is your **jasmineNodeOpts.defaultTimeoutInterval** set to?
Mine is set to 260000, equivalent to 260 seconds.
```
{ seleniumAddress: 'http://localhost:4444/wd/hub',
  specs: [ '/Users/**/**/**/automation/angular_automation/scripts/web/web_auto_delivery/web_auto_delivery.js' ],
  capabilities: 
   { platform: 'MAC',
     browserName: 'chrome',
     chromeOptions: { prefs: [Object] } },
  onPrepare: [Function: onPrepare],
  jasmineNodeOpts: { defaultTimeoutInterval: 260000 } }
```
I am also using Protractor Version 4.0.11 and Selenium 3.3.1

That's all I have, hope it helps with the issue.

**Comment by suzy123** [comment]
Thanks. My issue has been resolved. I was using very large value in defaultTimeoutInterval which was causing problem.

**Comment by makwanaparth94** [comment]
Scenario in my case is:
Currently I automate a site using a protractor but that site also consumes swagger ui api.So my question is can we do automation of protractor using those api?

**Comment by alejovicu** [comment]
I'm getting the same issue "_A Jasmine spec timed out. Resetting the WebDriver Control Flow_." When I run spec by spec everything works as expected. But, when I run all the regression some tests fail randomly. 
I already changed the jasmine.DEFAULT_TIMEOUT_INTERVAL to 10 minutes but still failing for suites that executed individually takes just less than a minute.

**Comment by vlad-danaila** [comment]
Hello, I am using Protractor. I get the same issue when testing on IE, for Chrome and Firefox it works fine.
I used some speciffic configurations for IE in order to make it work. Please find below the my conf.js file:

exports.config = {
    framework: 'jasmine',
    seleniumAddress: 'http://localhost:4444/wd/hub',
    specs: ['<<your specs>>'],
    multiCapabilities: [
        {
            browserName: 'chrome'
        }, {
            browserName: 'firefox'
        },
        {
            browserName: 'internet explorer',
            browserAttachTimeout: 10000,
            initialBrowserUrl: '<<your url>>'
        }
    ]
};

Please keep in mind you need to previously have drivers downloaded for each browser. You do that using the selenium webdriver-manager. Protractor has its own in node-modules/webdriver-manager.

**Comment by Aswini2205** [comment]
Hi, I also have a similar issue. Any update?

**Comment by marconemm** [comment]
Hi, I also have a similar issue. Any update?

**Comment by marconemm** [comment]
Hi, I also have a similar issue since the first example like de Protractor "GET STARTED" documentation [gege.](http://angular.github.io/protractor/#/). Below is my troubleshoot log and webdriver-manager server log:

**Troubleshoot log:**
```
$-> protractor ./config/conf.js  --troubleshoot
[22:49:23] D/launcher - Running with --troubleshoot
[22:49:23] D/launcher - Protractor version: 7.0.0
[22:49:23] D/launcher - Your base url for tests is undefined
[22:49:23] I/launcher - Running 1 instances of WebDriver
[22:49:23] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[22:49:24] D/runner - WebDriver session successfully started with capabilities Capabilities {
  map_: Map(17) {
    'acceptInsecureCerts' => false,
    'browserName' => 'chrome',
    'browserVersion' => '96.0.4664.45',
    'chrome' => {
      chromedriverVersion: '96.0.4664.45 (76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947})',
      userDataDir: '/tmp/.com.google.Chrome.Aq3UZP'
    },
    'goog:chromeOptions' => { debuggerAddress: 'localhost:39139' },
    'networkConnectionEnabled' => false,
    'pageLoadStrategy' => 'normal',
    'platformName' => 'linux',
    'proxy' => {},
    'setWindowRect' => true,
    'strictFileInteractability' => false,
    'timeouts' => { implicit: 0, pageLoad: 300000, script: 30000 },
    'unhandledPromptBehavior' => 'dismiss and notify',
    'webauthn:extension:credBlob' => true,
    'webauthn:extension:largeBlob' => true,
    'webauthn:virtualAuthenticators' => true,
    'webdriver.remote.sessionid' => '1169620a0503e3bca82b215a0e73be70'
  }
}
[22:49:24] D/runner - Running with spec files /home/mmmendonca1/Documents/ProtractorProjects/automation_example/tests/todo-spec.js
Started
[22:50:14] E/protractor - Could not find Angular on page https://angularjs.org/ : retries looking for angular exceeded
FA Jasmine spec timed out. Resetting the WebDriver Control Flow.


Failures:
1) angularjs homepage todo list should add a todo
  Message:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at listOnTimeout (node:internal/timers:557:17)
        at processTimers (node:internal/timers:500:7)
  Message:
    Failed: Angular could not be found on the page https://angularjs.org/. If this is not an Angular application, you may need to turn off waiting for Angular.
                              Please see 
                              https://github.com/angular/protractor/blob/master/docs/timeouts.md#waiting-for-angular-on-page-load
  Stack:
    Error: Angular could not be found on the page https://angularjs.org/. If this is not an Angular application, you may need to turn off waiting for Angular.
                              Please see 
                              https://github.com/angular/protractor/blob/master/docs/timeouts.md#waiting-for-angular-on-page-load
        at /home/mmmendonca1/.nvm/versions/node/v16.13.0/lib/node_modules/protractor/built/browser.js:718:27
        at ManagedPromise.invokeCallback_ (/home/mmmendonca1/.nvm/versions/node/v16.13.0/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1376:14)
        at TaskQueue.execute_ (/home/mmmendonca1/.nvm/versions/node/v16.13.0/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:3084:14)
        at TaskQueue.executeNext_ (/home/mmmendonca1/.nvm/versions/node/v16.13.0/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:3067:27)
        at /home/mmmendonca1/.nvm/versions/node/v16.13.0/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2927:27
        at /home/mmmendonca1/.nvm/versions/node/v16.13.0/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:668:7
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
    From: Task: Run it("should add a todo") in control flow
        at UserContext.<anonymous> (/home/mmmendonca1/.nvm/versions/node/v16.13.0/lib/node_modules/protractor/node_modules/jasminewd2/index.js:94:19)
    From asynchronous test: 
    Error
        at Suite.<anonymous> (/home/mmmendonca1/Documents/ProtractorProjects/automation_example/tests/todo-spec.js:2:2)
        at Object.<anonymous> (/home/mmmendonca1/Documents/ProtractorProjects/automation_example/tests/todo-spec.js:1:1)
        at Module._compile (node:internal/modules/cjs/loader:1101:14)
        at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
        at Module.load (node:internal/modules/cjs/loader:981:32)
        at Function.Module._load (node:internal/modules/cjs/loader:822:12)

1 spec, 1 failure
Finished in 49.988 seconds

[22:50:14] I/launcher - 0 instance(s) of WebDriver still running
[22:50:14] I/launcher - chrome #01 failed 1 test(s)
[22:50:14] I/launcher - overall: 1 failed spec(s)
[22:50:14] E/launcher - Process exited with error code 1
```

**webdriver-manager server log:**

```
$-> webdriver-manager start
[22:49:18] I/start - java -Djava.security.egd=file:///dev/./urandom -Dwebdriver.gecko.driver=/home/mmmendonca1/.nvm/versions/node/v16.13.0/lib/node_modules/protractor/node_modules/webdriver-manager/selenium/geckodriver-v0.30.0 -Dwebdriver.chrome.driver=/home/mmmendonca1/.nvm/versions/node/v16.13.0/lib/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_96.0.4664.45 -jar /home/mmmendonca1/.nvm/versions/node/v16.13.0/lib/node_modules/protractor/node_modules/webdriver-manager/selenium/selenium-server-standalone-3.141.59.jar -port 4444
[22:49:18] I/start - seleniumProcess.pid: 726087
22:49:18.408 INFO [GridLauncherV3.parse] - Selenium server version: 3.141.59, revision: e82be7d358
22:49:18.446 INFO [GridLauncherV3.lambda$buildLaunchers$3] - Launching a standalone Selenium Server on port 4444
2021-11-30 22:49:18.466:INFO::main: Logging initialized @163ms to org.seleniumhq.jetty9.util.log.StdErrLog
22:49:18.587 INFO [WebDriverServlet.<init>] - Initialising WebDriverServlet
22:49:18.633 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 4444
22:49:23.758 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "browserName": "chrome",
  "count": 1
}
22:49:23.759 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
Starting ChromeDriver 96.0.4664.45 (76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}) on port 29048
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
22:49:24.203 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
22:49:24.247 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session 1169620a0503e3bca82b215a0e73be70 (org.openqa.selenium.chrome.ChromeDriverService)
22:50:14.346 INFO [ActiveSessions$1.onStop] - Removing session 1169620a0503e3bca82b215a0e73be70 (org.openqa.selenium.chrome.ChromeDriverService)
```

**Comment by marconemm** [comment]
Hi, I also have a similar issue since the first example like the Protractor [GET STARTED](http://angular.github.io/protractor/#/) documentation.

Following below is my troubleshoot log and webdriver-manager server log:

**Troubleshoot log:**
```
$-> protractor ./config/conf.js  --troubleshoot
[22:49:23] D/launcher - Running with --troubleshoot
[22:49:23] D/launcher - Protractor version: 7.0.0
[22:49:23] D/launcher - Your base url for tests is undefined
[22:49:23] I/launcher - Running 1 instances of WebDriver
[22:49:23] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[22:49:24] D/runner - WebDriver session successfully started with capabilities Capabilities {
  map_: Map(17) {
    'acceptInsecureCerts' => false,
    'browserName' => 'chrome',
    'browserVersion' => '96.0.4664.45',
    'chrome' => {
      chromedriverVersion: '96.0.4664.45 (76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947})',
      userDataDir: '/tmp/.com.google.Chrome.Aq3UZP'
    },
    'goog:chromeOptions' => { debuggerAddress: 'localhost:39139' },
    'networkConnectionEnabled' => false,
    'pageLoadStrategy' => 'normal',
    'platformName' => 'linux',
    'proxy' => {},
    'setWindowRect' => true,
    'strictFileInteractability' => false,
    'timeouts' => { implicit: 0, pageLoad: 300000, script: 30000 },
    'unhandledPromptBehavior' => 'dismiss and notify',
    'webauthn:extension:credBlob' => true,
    'webauthn:extension:largeBlob' => true,
    'webauthn:virtualAuthenticators' => true,
    'webdriver.remote.sessionid' => '1169620a0503e3bca82b215a0e73be70'
  }
}
[22:49:24] D/runner - Running with spec files /home/mmmendonca1/Documents/ProtractorProjects/automation_example/tests/todo-spec.js
Started
[22:50:14] E/protractor - Could not find Angular on page https://angularjs.org/ : retries looking for angular exceeded
FA Jasmine spec timed out. Resetting the WebDriver Control Flow.


Failures:
1) angularjs homepage todo list should add a todo
  Message:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at listOnTimeout (node:internal/timers:557:17)
        at processTimers (node:internal/timers:500:7)
  Message:
    Failed: Angular could not be found on the page https://angularjs.org/. If this is not an Angular application, you may need to turn off waiting for Angular.
                              Please see 
                              https://github.com/angular/protractor/blob/master/docs/timeouts.md#waiting-for-angular-on-page-load
  Stack:
    Error: Angular could not be found on the page https://angularjs.org/. If this is not an Angular application, you may need to turn off waiting for Angular.
                              Please see 
                              https://github.com/angular/protractor/blob/master/docs/timeouts.md#waiting-for-angular-on-page-load
        at /home/mmmendonca1/.nvm/versions/node/v16.13.0/lib/node_modules/protractor/built/browser.js:718:27
        at ManagedPromise.invokeCallback_ (/home/mmmendonca1/.nvm/versions/node/v16.13.0/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1376:14)
        at TaskQueue.execute_ (/home/mmmendonca1/.nvm/versions/node/v16.13.0/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:3084:14)
        at TaskQueue.executeNext_ (/home/mmmendonca1/.nvm/versions/node/v16.13.0/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:3067:27)
        at /home/mmmendonca1/.nvm/versions/node/v16.13.0/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2927:27
        at /home/mmmendonca1/.nvm/versions/node/v16.13.0/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:668:7
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
    From: Task: Run it("should add a todo") in control flow
        at UserContext.<anonymous> (/home/mmmendonca1/.nvm/versions/node/v16.13.0/lib/node_modules/protractor/node_modules/jasminewd2/index.js:94:19)
    From asynchronous test: 
    Error
        at Suite.<anonymous> (/home/mmmendonca1/Documents/ProtractorProjects/automation_example/tests/todo-spec.js:2:2)
        at Object.<anonymous> (/home/mmmendonca1/Documents/ProtractorProjects/automation_example/tests/todo-spec.js:1:1)
        at Module._compile (node:internal/modules/cjs/loader:1101:14)
        at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
        at Module.load (node:internal/modules/cjs/loader:981:32)
        at Function.Module._load (node:internal/modules/cjs/loader:822:12)

1 spec, 1 failure
Finished in 49.988 seconds

[22:50:14] I/launcher - 0 instance(s) of WebDriver still running
[22:50:14] I/launcher - chrome #01 failed 1 test(s)
[22:50:14] I/launcher - overall: 1 failed spec(s)
[22:50:14] E/launcher - Process exited with error code 1
```

**webdriver-manager server log:**

```
$-> webdriver-manager start
[22:49:18] I/start - java -Djava.security.egd=file:///dev/./urandom -Dwebdriver.gecko.driver=/home/mmmendonca1/.nvm/versions/node/v16.13.0/lib/node_modules/protractor/node_modules/webdriver-manager/selenium/geckodriver-v0.30.0 -Dwebdriver.chrome.driver=/home/mmmendonca1/.nvm/versions/node/v16.13.0/lib/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_96.0.4664.45 -jar /home/mmmendonca1/.nvm/versions/node/v16.13.0/lib/node_modules/protractor/node_modules/webdriver-manager/selenium/selenium-server-standalone-3.141.59.jar -port 4444
[22:49:18] I/start - seleniumProcess.pid: 726087
22:49:18.408 INFO [GridLauncherV3.parse] - Selenium server version: 3.141.59, revision: e82be7d358
22:49:18.446 INFO [GridLauncherV3.lambda$buildLaunchers$3] - Launching a standalone Selenium Server on port 4444
2021-11-30 22:49:18.466:INFO::main: Logging initialized @163ms to org.seleniumhq.jetty9.util.log.StdErrLog
22:49:18.587 INFO [WebDriverServlet.<init>] - Initialising WebDriverServlet
22:49:18.633 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 4444
22:49:23.758 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "browserName": "chrome",
  "count": 1
}
22:49:23.759 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
Starting ChromeDriver 96.0.4664.45 (76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}) on port 29048
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
22:49:24.203 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
22:49:24.247 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session 1169620a0503e3bca82b215a0e73be70 (org.openqa.selenium.chrome.ChromeDriverService)
22:50:14.346 INFO [ActiveSessions$1.onStop] - Removing session 1169620a0503e3bca82b215a0e73be70 (org.openqa.selenium.chrome.ChromeDriverService)
```
