### ISSUE TITLE
Sendkeys is sending the incomplete string

### ISSUE THREAD

**Issue by rafaelcs** [angular/protractor#4280]
Hello folks,

I'm having trouble sending sendkeys in my application. Sendkeys itself works, but sometimes it does not send the full string to the field of my application. I tried to solve this in two different ways (as you can see the examples below), but even then this error occurs sometimes.

My application is running in Codeship (CI) and also runs locally, in both environments the error occurs

---

- Node Version: `Node Version read from package.json: 6.2.2; Node Version used: 6.2.2`
- Protractor Version: `5.1.1`
- Angular Version: `I'm not using angular for that`
- Browser(s): `ChromeDriver; Driver info: chromedriver=2.29.461571`
- Operating System and Version `platform=Linux 4.2.0-42-generic x86_64`
- Your protractor configuration file: See [here](https://gist.github.com/rafaelcs/ee3d86709f1434480b1f42fe4fc4d5e9)
- A relevant example test: `I've added two examples just below`
- Output from running the test
![image](https://cloud.githubusercontent.com/assets/8113555/25962412/0478fe84-3654-11e7-8fef-4f11d02a2644.png)
- Steps to reproduce the bug: I have already tried using two ways to solve this, but with both ways the same error occurs
```
        this.name.click();
        this.name.sendKeys(text);
```
```
        var nameValue = 'odit';
        nameValue.split('').forEach((c) => this.name.sendKeys(c));
```
- The URL you are running your tests against (if relevant): `Private project, I can not send the url`

**Comment by ctnordcl** [comment]
I've been seeing this as well. It's been failing for me on Chrome.

**Comment by NickTomlin** [comment]
Very interesting. Just curious, do you see this when running the [example tests](https://github.com/angular/protractor/blob/master/example/example_spec.js) or just in your application? What happens if you downgrade your chromedriver version?

**Comment by rafaelcs** [comment]
@NickTomlin I'll do these tests soon and let you know

**Comment by NickTomlin** [comment]
@rafaelcs great, thanks!

**Comment by rafaelcs** [comment]
@NickTomlin Using chromedriver version 2.28, the problem is the same. See:

![image](https://cloud.githubusercontent.com/assets/8113555/26087104/54e1c972-39c5-11e7-9eaa-042353b7d065.png)

The error did not occur with the example script

**Comment by cnishina** [comment]
Just from the information provided, it looks like it is not an Angular page. If you turn ignoreSynchronization to true, then you are responsible for your own waiting. Waiting could mean that:

- you are waiting arbitrarily for your page to load / stabilize
- you chain your promises with `then` methods to wait for previous promises to resolve
- a combination of arbitrarily waiting and chaining promises

Something like this should work with ignoreSynchronization set to true.
```
import {promise as wdpromise} from 'selenium-webdriver';

someFunction = (): wdpromise.Promise<any> => {
  return this.name.click().then((): wdpromise.Promise<any> => {
    return this.name.sendKeys(text);
  });
}
```

**Comment by wswebcreation** [comment]
@rafaelcs 

Did you manage to solve this or is it still open? Did you also tried the solution @cnishina provided?

There is also no activity on this issue since the 17th of May. If there is no further activity at the end of the week I assume the issue is solved and I'll close this issue.

**Comment by victornoel** [comment]
@wswebcreation I'm seeing this issue regularly but indeterministically on my project too… I don't think it is solved.

**Comment by wswebcreation** [comment]
@victornoel 

Do you see this when running the [example tests](https://github.com/angular/protractor/blob/master/example/example_spec.js) or just in your application?

**Comment by victornoel** [comment]
@wswebcreation 
1. it does not happen with those tests
2. it only happens on one specific place in my application, but not on any other
3. it happens sometimes, usually it is dependent on performances

I'm using chormium 61, chromedriver 2.32, protractor 5.1.2 

I can try to replicate it on a smaller example, but I suspect it won't happen because it is tied to the fact my application is complex. I will try to replicate it deterministically on my application and provide you with instructions to witness it maybe first :)

**Comment by wswebcreation** [comment]
@victornoel 

Tnx. I happened to see something similar in a previous project I was working on. The validations on the input made Protractor go completely crazy, I fixed it with a `browser.executeScript('//some code injection');`  to get it working. Meaning I was not really testing the input, but the input was more testing my patience ;-)

**Comment by victornoel** [comment]
@wswebcreation ah yes, me too there is some validation (from angular reactive forms) on this input I'm testing!
