### ISSUE TITLE
Protractor 5.4.2 is not compatible with Chrome 77

### ISSUE THREAD

**Issue by zuzusik** [angular/protractor#5312]
Chrome 77 just got released, which is not compatible with Protractor `5.4.2`:

```
[15:06:46] E/runner - Unable to start a WebDriver session.
[15:06:46] E/launcher - Error: SessionNotCreatedError: session not created: 
  This version of ChromeDriver only supports Chrome version 75
  (Driver info: chromedriver=75.0.3770.90 (a6dcaf7e3ec6f70a194cc25e8149475c6590e025-refs/branch-heads/3770@{#1003}),platform=Mac OS X 10.14.6 x86_64)
```

Specifying later version of chromedriver works, but it is pretty much not a robust solution, as it requires to specify the exact version of driver:

`/webdriver-manager update --versions.chrome=77.0.3865.40`

`--versions.chrome=77` doesn't work

**Comment by garethbowen** [comment]
Issue also reported here: https://github.com/angular/webdriver-manager/issues/420

**Comment by cnishina** [comment]
Okay this should work now. You'll need to get the latest webdriver-manager version 12.1.7. This should work from here on in to get the latest release of chromedriver.

**Comment by cnishina** [comment]
To get the latest you might need to remove the node_modules folder and redownload your node modules or do a force install of your node modules (npm i -f)

**Comment by prabahar-lilly** [comment]
> Okay this should work now. You'll need to get the latest webdriver-manager version 12.1.7. This should work from here on in to get the latest release of chromedriver.

Upgrading webdriver-manager to 12.1.7 works for me. Thanks

**Comment by huiaic** [comment]
For those using Travis, you'll also need to change your distribution to Xenial because [Chrome 77 stopped supporting Trusty ](https://travis-ci.community/t/travis-is-downloading-older-chrome-versions-in-place-of-chrome-stable/5040/3), ie. in `travis.yml`:

    dist: xenial
    addons:
       chrome: stable

**Comment by DesHorsley** [comment]
I'm still seeing this issue, I'm running `ng e2e` 
In the logs I'm seeing that it is using the correct driver: 
```
[22:05:30] I/update - chromedriver: chromedriver_77.0.3865.40 up to date
[22:05:31] I/launcher - Running 1 instances of WebDriver
[22:05:31] I/direct - Using ChromeDriver directly...
[22:05:33] E/runner - Unable to start a WebDriver session.
[22:05:33] E/launcher - Error: Error: Server terminated early with status 127
```
Any thoughts?

**Comment by kanyIO** [comment]
I kept hitting blockers after updating chrome driver to latest with the error ```
"E/launcher - session not created: This version of ChromeDriver only supports Chrome version 75
  (Driver info: chromedriver=75.0.3770.90"
```
but reinstalling protractor globally worked for me.

**Comment by Wisdomb33r** [comment]
@DesHorsley I had this obscure error message when CI (Bamboo in my case) was trying to run e2e tests. This was due to Linux X11 being not loaded for automatic builds. You need to run the e2e tests with a headless Chrome to avoid needing X11. My `protractor.conf.js` : 

<pre><code>
capabilities: {
    'browserName': 'chrome',
    'chromeOptions': {
      'args': ['--headless']
    }
  },
</code></pre>
